### ISSUE TITLE
After install, falling in gitbook build

### ISSUE THREAD

**Issue by huxulm** [DocsHome/nginx-docs#20]
```
Failed to load prism syntax: ngixn
{ Error: Cannot find module 'prismjs/components/prism-ngixn.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at requireSyntax (/home/jackdon/git_repos/nginx-docs/node_modules/gitbook-plugin-prism/index.js:31:3)
    at Object.code (/home/jackdon/git_repos/nginx-docs/node_modules/gitbook-plugin-prism/index.js:103:11)
    at Record.TemplateBlock.applyBlock (/root/.gitbook/versions/3.2.3/lib/models/templateBlock.js:205:23)
    at /root/.gitbook/versions/3.2.3/lib/output/getModifiers.js:56:33
    at /root/.gitbook/versions/3.2.3/lib/output/modifiers/highlightCode.js:47:24
    at /root/.gitbook/versions/3.2.3/lib/output/modifiers/editHTMLElement.js:11:16 code: 'MODULE_NOT_FOUND' }
Failed to load prism syntax: ngixn
{ Error: Cannot find module 'prismjs/components/prism-ngixn.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at requireSyntax (/home/jackdon/git_repos/nginx-docs/node_modules/gitbook-plugin-prism/index.js:31:3)
    at Object.code (/home/jackdon/git_repos/nginx-docs/node_modules/gitbook-plugin-prism/index.js:103:11)
    at Record.TemplateBlock.applyBlock (/root/.gitbook/versions/3.2.3/lib/models/templateBlock.js:205:23)
    at /root/.gitbook/versions/3.2.3/lib/output/getModifiers.js:56:33
    at /root/.gitbook/versions/3.2.3/lib/output/modifiers/highlightCode.js:47:24
    at /root/.gitbook/versions/3.2.3/lib/output/modifiers/editHTMLElement.js:11:16 code: 'MODULE_NOT_FOUND' }
Failed to load prism syntax: ngixn
{ Error: Cannot find module 'prismjs/components/prism-ngixn.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at requireSyntax (/home/jackdon/git_repos/nginx-docs/node_modules/gitbook-plugin-prism/index.js:31:3)
    at Object.code (/home/jackdon/git_repos/nginx-docs/node_modules/gitbook-plugin-prism/index.js:103:11)
    at Record.TemplateBlock.applyBlock (/root/.gitbook/versions/3.2.3/lib/models/templateBlock.js:205:23)
    at /root/.gitbook/versions/3.2.3/lib/output/getModifiers.js:56:33
    at /root/.gitbook/versions/3.2.3/lib/output/modifiers/highlightCode.js:47:24
    at /root/.gitbook/versions/3.2.3/lib/output/modifiers/editHTMLElement.js:11:16 code: 'MODULE_NOT_FOUND' }
Failed to load prism syntax: ngixn
{ Error: Cannot find module 'prismjs/components/prism-ngixn.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at requireSyntax (/home/jackdon/git_repos/nginx-docs/node_modules/gitbook-plugin-prism/index.js:31:3)
    at Object.code (/home/jackdon/git_repos/nginx-docs/node_modules/gitbook-plugin-prism/index.js:103:11)
    at Record.TemplateBlock.applyBlock (/root/.gitbook/versions/3.2.3/lib/models/templateBlock.js:205:23)
    at /root/.gitbook/versions/3.2.3/lib/output/getModifiers.js:56:33
    at /root/.gitbook/versions/3.2.3/lib/output/modifiers/highlightCode.js:47:24
    at /root/.gitbook/versions/3.2.3/lib/output/modifiers/editHTMLElement.js:11:16 code: 'MODULE_NOT_FOUND' }
Failed to load prism syntax: pm
{ Error: Cannot find module 'prismjs/components/prism-pm.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at requireSyntax (/home/jackdon/git_repos/nginx-docs/node_modules/gitbook-plugin-prism/index.js:31:3)
    at Object.code (/home/jackdon/git_repos/nginx-docs/node_modules/gitbook-plugin-prism/index.js:103:11)
    at Record.TemplateBlock.applyBlock (/root/.gitbook/versions/3.2.3/lib/models/templateBlock.js:205:23)
    at /root/.gitbook/versions/3.2.3/lib/output/getModifiers.js:56:33
    at /root/.gitbook/versions/3.2.3/lib/output/modifiers/highlightCode.js:47:24
    at /root/.gitbook/versions/3.2.3/lib/output/modifiers/editHTMLElement.js:11:16 code: 'MODULE_NOT_FOUND' }
Failed to load prism syntax: pm
{ Error: Cannot find module 'prismjs/components/prism-pm.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at requireSyntax (/home/jackdon/git_repos/nginx-docs/node_modules/gitbook-plugin-prism/index.js:31:3)
    at Object.code (/home/jackdon/git_repos/nginx-docs/node_modules/gitbook-plugin-prism/index.js:103:11)
    at Record.TemplateBlock.applyBlock (/root/.gitbook/versions/3.2.3/lib/models/templateBlock.js:205:23)
    at /root/.gitbook/versions/3.2.3/lib/output/getModifiers.js:56:33
    at /root/.gitbook/versions/3.2.3/lib/output/modifiers/highlightCode.js:47:24
    at /root/.gitbook/versions/3.2.3/lib/output/modifiers/editHTMLElement.js:11:16 code: 'MODULE_NOT_FOUND' }
Failed to load prism syntax: pm
{ Error: Cannot find module 'prismjs/components/prism-pm.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at requireSyntax (/home/jackdon/git_repos/nginx-docs/node_modules/gitbook-plugin-prism/index.js:31:3)
    at Object.code (/home/jackdon/git_repos/nginx-docs/node_modules/gitbook-plugin-prism/index.js:103:11)
    at Record.TemplateBlock.applyBlock (/root/.gitbook/versions/3.2.3/lib/models/templateBlock.js:205:23)
    at /root/.gitbook/versions/3.2.3/lib/output/getModifiers.js:56:33
    at /root/.gitbook/versions/3.2.3/lib/output/modifiers/highlightCode.js:47:24
    at /root/.gitbook/versions/3.2.3/lib/output/modifiers/editHTMLElement.js:11:16 code: 'MODULE_NOT_FOUND' }
```

**Comment by oopsguy** [comment]
@jackdon Thanks, fixed it.
